# Generated by Django 3.0.4 on 2021-06-04 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210604_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 14, 31, 2, 773300, tzinfo=utc)),
        ),
    ]
