# Generated by Django 3.0.4 on 2020-04-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200331_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.CharField(blank=True, default='user', max_length=32, null=True),
        ),
    ]
