# Generated by Django 3.0.4 on 2020-04-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200331_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='usuario_avatar',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='avatar_padrao',
        ),
        migrations.AddField(
            model_name='avatar',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
