# Generated by Django 3.0.4 on 2020-04-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200401_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='birthdate',
            new_name='aniversario',
        ),
    ]
