# Generated by Django 3.0.4 on 2021-06-04 14:17

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201016_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='tipo_telefone',
            field=models.CharField(blank=True, choices=[('FIX', 'Fixo'), ('CEL', 'Celular'), ('FAX', 'Fax'), ('OUT', 'Outro')], default='CEL', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(help_text='Utilize no máximo 15 caracteres. São permitidos letras, números e "." "-" "_"', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.-_]+$'), 'Digite um nome de usuário válido.', 'Inválido.')], verbose_name='Nome de Usuário'),
        ),
    ]
