# Generated by Django 3.0.4 on 2021-06-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210604_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco_padrao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='site_padrao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone_padrao',
        ),
    ]
